### ISSUE TITLE
Filedownload in Firefox

### ISSUE THREAD

**Issue by docoli** [BurdaPraha/oc_invoice_pdf#2]
Hey there,
i have found a small issue in your code regarding the filedownload in firefox. Currently in my firefox (59.0.2 (64-Bit)) this is not working properly.

I would recommend to replace the single quotes for the filename with escaped double quotes to make this thing working on firefox to.

```php
filename=\"" . $basename($location) . "\"
```

Cheers :-)
https://github.com/BurdaPraha/oc_invoice_pdf/blob/a4f68c9e588ff4b2e3614c606154a27fe10d994e/src/shortcuts.php#L82

**Comment by landsman** [comment]
Thank you for issue, I'll test it on Firefox.
